blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://docs.example.com
    about: Check our documentation first
  - name: 💬 Discussions
    url: https://github.com/org/repo/discussions
    about: Ask questions and discuss ideas
  - name: 🔒 Security Issue
    url: https://github.com/org/repo/security/advisories
    about: Report security vulnerabilities privately
